resources:
  - repo: self
queue:
  name: Hosted Ubuntu 1604
trigger:
  - master
  - releases/*
pr:
  - master
  - releases/*
steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: 'Use Yarn 1.x'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn install'
    inputs:
      Arguments: install

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn run test-ci'
    inputs:
      Arguments: 'run test-ci'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: JUnit
      testResultsFiles: ./junit.xml

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    inputs:
      codeCoverageTool: Cobertura

      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/'

      failIfCoverageEmpty: true

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn build'
    inputs:
      Arguments: build

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/build/'

      Contents: '**/*'

      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
